theme: jekyll-theme-leap-day
title: MetaZoo JP
description: 後生動物の初期の系統・進化についてまとめることを目指すWebサイトです
baseurl: "/metazoo-jp"
url: "https://mz9862.github.io"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
plugins:
  - jekyll-seo-tag
