theme: jekyll-theme-cayman
title: MetaZoo JP
description: 後生動物の初期の系統・進化についてまとめることを目指すWebサイトです
lang: ja_JP
markdown: kramdown
highlighter: rouge
email: mz9862.github@gmail.com
author:
  name: MZ9862
  email: mz9862.github@gmail.com
url: "https://mz9862.github.io"
baseurl: "/metazoo-jp"
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
google_analytics: G-TRZTCBF6R7
